In [1]:
import pandas as pd
import numpy as np
import datetime
import yfinance as yf
#import pandas.tseries.offsets.BusinessDay
from pandas.tseries.offsets import BDay
from platform import python_version
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [2]:
data=pd.read_csv("indiabulls.csv")

In [3]:
data["sma50"]=data["Adj Close"].rolling(window=50).mean()

In [4]:
data=data[49:].reset_index(drop=True)

In [5]:
data["Date"]=data['Date'].apply(lambda x :datetime.datetime.strptime(x,"%Y-%m-%d"))

In [143]:
trade_log

,Trade_type,entry_time,exit_time,entry_price,exit_price,pnl
0,BUY,2013-10-24 00:00:00,NaN,125.672417,NaN,NaN
1,SELL,NaN,2014-01-16 00:00:00,NaN,148.023178,NaN
2,BUY,2014-01-20 00:00:00,NaN,149.427963,NaN,NaN
3,SELL,NaN,2014-01-24 00:00:00,NaN,147.467834,NaN
4,BUY,2014-03-13 00:00:00,NaN,144.931366,NaN,NaN
...,...,...,...,...,...,...
115,SELL,NaN,2021-12-17 00:00:00,NaN,233.149994,NaN
116,BUY,2022-04-05 00:00:00,NaN,178.550003,NaN,NaN
117,SELL,NaN,2022-04-08 00:00:00,NaN,172.399994,NaN
118,BUY,2022-04-11 00:00:00,NaN,172.949997,NaN,NaN
119,SELL,NaN,2022-04-12 00:00:00,NaN,167.100006,NaN

In [162]:
long_position=0
sell_position=0
trade_log=pd.DataFrame(columns=["Trade_type","long_entry_time","long_exit_time","short_entry_time","short_exit_time","short_entry_price","short_exit_price","long_entry_price","long_exit_price","pnl"])

for index,today in data.iterrows():
    previous_day=data.iloc[index-1]
    
    if (previous_day['Adj Close']<previous_day['sma50'])&(today['Adj Close']>today['sma50'])&((long_position==0)or(sell_position==1)):
            ## fresh long call##
                
        if (long_position==0) & (sell_position==0) :
            long_position=1                                         
            entry_price=today['Adj Close']
            print("loop1")
            entry_time=today["Date"]
                                  
            trade_log=trade_log.append({"Trade_type":"BUY","long_entry_time":entry_time,"long_entry_price":entry_price},ignore_index=True)
         ## sell exit ###################################################  
        
        if  (sell_position==1) & (long_position==0):  
                      
             exit_price=today['Adj Close']
             print("loop2")
             exit_time=today["Date"]                      
             sell_position=0
             long_position=1
             trade_log=trade_log.append({"Trade_type":"BUY","short_exit_time":exit_time,"short_exit_price":exit_price},ignore_index=True)
             #trade_log=trade_log.append({"Trade_type":"BUY","exit_time":exit_time,"exit_price":exit_price},ignore_index=True)
                            
    if(previous_day['Adj Close']>previous_day['sma50'])&(today['Adj Close']<today['sma50'])&((long_position==1)or(sell_position==0)):
          
        ### frsh sell call ############################################################
        
        if (sell_position==0) &(long_position==0): 
              sell_position=1 
              print("loop3")
              entry_price=today["Adj Close"]
              entry_time=today["Date"]
              trade_log=trade_log.append({"Trade_type":"SELL","short_entry_time":entry_time,"short_entry_price":entry_price},ignore_index=True)
                  
        
         ## long Exit#############################################
            
        if (long_position==1)&(sell_position==0) :
             long_position=0
             sell_position=1
             print("loop4")
             exit_price=today['Adj Close']
             exit_time=today["Date"]
             trade_log=trade_log.append({"Trade_type":"SELL","long_exit_time":exit_time,"long_exit_price":exit_price},ignore_index=True)

loop1
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4
loop2
loop4

In [164]:
trade_log.to_csv("trade_log.csv")